import Head from 'next/head'
import Header from "../components/Header"
import Balance from "../components/Balance"
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useAccount } from 'wagmi'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const { address} = useAccount()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Header/>
        <h1>Predictoor</h1>
        <Balance/>
      </main>
    </>
  )
}
