import { AssetsContainer } from '@/components/AssetsContainer'
import Balance from '@/components/Balance'
import Banner from '@/components/Banner'
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import styles from '@/styles/Home.module.css'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import 'react-notifications/lib/notifications.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Predictoor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-thumbnail.png" />
      </Head>
      <Banner />
      <main className={`${styles.main} ${inter.className}`}>
        <Header />
        <div className={styles.description}>
          <p className={styles.oneliner}>
            Accurate price predictions for your favorite crypto assets
          </p>
          <Balance />
        </div>
        <AssetsContainer />
        <Footer />
      </main>
    </>
  )
}
