import Banner from '@/components/Banner'
import styles from '@/styles/Home.module.css'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import 'react-notifications/lib/notifications.css'
import AgreementModal from './AgreementModal'
import Footer from './Footer'
import Header from './Header'

const inter = Inter({ subsets: ['latin'] })

export type TMainWrapperProps = {
  children: React.ReactNode
  withBanner?: boolean
  isWalletActive?: boolean
}

export default function MainWrapper({
  children,
  withBanner = true,
  isWalletActive = true
}: TMainWrapperProps) {
  return (
    <>
      <Head>
        <title>Predictoor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-thumbnail.png" />
      </Head>
      {withBanner && <Banner />}
      <main className={`${styles.main} ${inter.className}`}>
        <AgreementModal />
        <Header isWalletActive={isWalletActive} />
        {children}
        <Footer />
      </main>
    </>
  )
}
